### ISSUE TITLE
IP 192.168.121.1 is not created

### ISSUE THREAD

**Issue by ulrichSchreiner** [metal-stack/mini-lab#5]
hi,

i normally use only `make control-plane` to startup the control plane locally in a cluster. Sadly this does not work if the IP adress `192.168.121.1` does not exist. This IP is created implicitly by using vagrant to spin off some machines which are not needed by the control plane (and which i don't want to spin of only to gather this IP).

my workaround is to do a 
~~~
sudo ip a add 192.168.121.1/24 dev eno1 label eno1:1
~~~
where `eno1` is my main interface on my machine. it would be great to do this automatically somewhere in the whole *machinery*

**Comment by Gerrit91** [comment]
Hey. Yes, that would make sense as you are not the first person who encountered this problem. I thought I have seen a vagrant command to create the network at some point in time... @mwindower @kolsa did one of you at some point added something regarding this issue?

**Comment by majst01** [comment]
same here, but its hard to figure out whats the interface to put this ip onto, on my machine its `wlp4s0`

**Comment by mwindower** [comment]
instead of assuming this ip or adding it to an existing interface, we could also adapt the `kind.config` to bind to all interfaces and inspect the ip of the kind container for the metal-api endpoint.
