### ISSUE TITLE
nip.io does not want to resolve 0.0.0.0

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/mini-lab#86]
```
❯ host test.0.0.0.0.nip.io
❯ host test.1.0.0.0.nip.io
test.1.0.0.0.nip.io has address 1.0.0.0
```

**Comment by majst01** [comment]
unsure, only recently linux added support for treating 0.0.0.0 as a valid address

**Comment by Gerrit91** [comment]
Looks like it's also an issue on my local machine. :thinking:

**Comment by Gerrit91** [comment]
It's an issue on my own machine resolving DNS.
